import { Game, Player, Team } from "./types";

export const games: Game[] = [
  {
    currentLine: [],
    id: "3jqki8x",
    timeStamp: 1741544522000,
    teamId: "j0v81y1",
    eventName: "",
    opponentName: "Lakeside",
    ourScore: 0,
    theirScore: 0,
    isOver: false,
    isUploaded: false,
    isArchived: false,
    points: [],
    halfAt: "points",
    hardCap: 75,
    startingOn: "offense",
    pointCap: 13,
    hasPossession: true,
  },
  {
    currentLine: [],
    id: "utpjp1u",
    timeStamp: 1773340473821,
    teamId: "j0v81y1",
    eventName: "",
    opponentName: "Maynard Jackson",
    ourScore: 0,
    theirScore: 1,
    isOver: false,
    isUploaded: false,
    isArchived: false,
    points: [],
    halfAt: "points",
    hardCap: 75,
    startingOn: "offense",
    pointCap: 13,
    hasPossession: true,
  },
  {
    currentLine: [],
    id: "0t2ejga",
    timeStamp: 1773340473821,
    teamId: "j0v81y1",
    eventName: "",
    opponentName: "Decatur",
    ourScore: 1,
    theirScore: 0,
    isOver: false,
    isUploaded: false,
    isArchived: false,
    points: [],
    halfAt: "points",
    hardCap: 75,
    startingOn: "offense",
    pointCap: 13,
    hasPossession: true,
  },
];

export const players: Player[] = [
  {
    id: "41lye44",
    name: "Seth L",
    number: 15,
    teamIDs: ["j0v81y1"],
    active: true,
    isArchived: false,
  },
  {
    id: "5yewgrb",
    name: "Calder Z",
    number: 65,
    teamIDs: ["j0v81y1"],
    active: true,
    isArchived: false,
  },
  {
    id: "441yi9r",
    name: "Lyosha V",
    number: 3,
    teamIDs: ["j0v81y1"],
    active: true,
    isArchived: false,
  },
  {
    id: "nogzjox",
    name: "Vishnu G",
    number: 5,
    teamIDs: ["j0v81y1"],
    active: true,
    isArchived: false,
  },
  {
    id: "e2nod78",
    name: "Micah K",
    number: 7,
    teamIDs: ["j0v81y1"],
    active: true,
    isArchived: false,
  },
  {
    id: "yjte1n6",
    name: "Jaden W",
    number: 9,
    teamIDs: ["j0v81y1"],
    active: true,
    isArchived: false,
  },
  {
    id: "1zgc2ux",
    name: "Julien T",
    number: 11,
    teamIDs: ["j0v81y1"],
    active: true,
    isArchived: false,
  },
  {
    id: "17dynu7",
    name: "Armando RH",
    number: 13,
    teamIDs: ["j0v81y1"],
    active: true,
    isArchived: false,
  },
  {
    id: "3sav9da",
    name: "Dom A",
    number: 19,
    teamIDs: ["j0v81y1"],
    active: true,
    isArchived: false,
  },
  {
    id: "415dq9q",
    name: "Parth P",
    number: 17,
    teamIDs: ["j0v81y1"],
    active: true,
    isArchived: false,
  },
  {
    id: "j0v81y1-unknown",
    name: "UNKNOWN",
    teamIDs: ["j0v81y1"],
    active: true,
    isArchived: false,
  },
];

export const teams: Team[] = [
  {
    id: "j0v81y1",
    name: "2026 Varsity Open AIS Eagles",
    playerIDs: [
      "41lye44",
      "5yewgrb",
      "441yi9r",
      "nogzjox",
      "e2nod78",
      "yjte1n6",
      "1zgc2ux",
      "17dynu7",
      "3sav9da",
      "415dq9q",
      "j0v81y1-unknown",
    ],
    gameIDs: ["3jqki8x", "utpjp1u", "0t2ejga"],
    isArchived: false,
    shortName: "AIS",
  },
  {
    id: "sg6uydo",
    name: "2026 Junior Varsity Women's AIS Eagles",
    playerIDs: [],
    gameIDs: [],
    isArchived: false,
    shortName: "AIS",
  },
  {
    id: "0pk3iv9",
    name: "2025 MS Open AIS Eagles",
    playerIDs: [],
    gameIDs: [],
    isArchived: false,
    shortName: "AIS",
  },
  {
    id: "v7f8lbf",
    name: "2024 MS Open AIS Eagles",
    playerIDs: [],
    gameIDs: [],
    isArchived: true,
    shortName: "AIS",
  },
];
